import { useMemo } from "react";

import { useQuery } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { StyleSheet, Text, View } from "react-native";

import { PrimaryButton } from "@/components/primary-button";
import { ScreenShell } from "@/components/screen-shell";
import { SectionHeader } from "@/components/section-header";
import { StatePanel } from "@/components/state-panel";
import { Surface } from "@/components/surface";
import { sentenceCase } from "@/lib/formatters";
import { mobileApi } from "@/lib/api/queries";
import { useAppTheme } from "@/lib/theme";

function asItems(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value
      .map((item) => {
        if (typeof item === "string") {
          return item;
        }
        if (item && typeof item === "object" && "description" in item) {
          return String((item as { description: unknown }).description);
        }
        return "";
      })
      .filter(Boolean);
  }
  return [];
}

export default function CompetitorDetailScreen() {
  const { colors } = useAppTheme();
  const params = useLocalSearchParams<{ id?: string }>();
  const competitorId = Number(params.id);

  const analysisQuery = useQuery({
    queryKey: ["mobile-competitor-analysis", competitorId],
    queryFn: () => mobileApi.getCompetitorAnalysis(competitorId),
    enabled: Number.isFinite(competitorId),
  });

  const threatLevel = useMemo(() => {
    const raw = (analysisQuery.data?.threat_assessment as Record<string, unknown> | undefined)?.threat_level;
    return raw ? sentenceCase(String(raw)) : "Monitoring";
  }, [analysisQuery.data]);

  if (analysisQuery.isLoading) {
    return (
      <ScreenShell>
        <StatePanel title="Loading analysis" body="Pulling SWOT, news, and threat scoring." loading />
      </ScreenShell>
    );
  }

  if (analysisQuery.isError || !analysisQuery.data) {
    return (
      <ScreenShell>
        <StatePanel title="Analysis unavailable" body="This competitor analysis could not be loaded right now." />
      </ScreenShell>
    );
  }

  const analysis = analysisQuery.data;
  const competitor = analysis.competitor as Record<string, unknown>;
  const swot = analysis.swot_analysis as Record<string, unknown>;
  const insights = analysis.strategic_insights ?? [];

  return (
    <ScreenShell>
      <View style={styles.header}>
        <Text style={[styles.kicker, { color: colors.accent }]}>Threat level {threatLevel}</Text>
        <Text style={[styles.title, { color: colors.text }]}>{String(competitor.name ?? "Competitor")}</Text>
        <Text style={[styles.body, { color: colors.textMuted }]}>
          {String(competitor.industry ?? competitor.sector ?? "Competitive intelligence profile")}
        </Text>
      </View>

      <View style={styles.grid}>
        <Surface style={styles.summaryCard}>
          <Text style={[styles.summaryLabel, { color: colors.textMuted }]}>Market share</Text>
          <Text style={[styles.summaryValue, { color: colors.text }]}>
            {competitor.market_share_percent ? `${Number(competitor.market_share_percent).toFixed(1)}%` : "--"}
          </Text>
        </Surface>
        <Surface style={styles.summaryCard}>
          <Text style={[styles.summaryLabel, { color: colors.textMuted }]}>Growth</Text>
          <Text style={[styles.summaryValue, { color: colors.text }]}>
            {competitor.revenue_growth_rate ? `${Number(competitor.revenue_growth_rate).toFixed(1)}%` : "--"}
          </Text>
        </Surface>
      </View>

      <View>
        <SectionHeader
          eyebrow="SWOT"
          title="Strategic readout"
          description="A fast mobile summary of strengths, weaknesses, and what matters next."
        />
        <Surface style={styles.swotCard}>
          <Text style={[styles.swotTitle, { color: colors.text }]}>Strengths</Text>
          {asItems(swot.strengths).map((item) => (
            <Text key={`s-${item}`} style={[styles.swotItem, { color: colors.textSoft }]}>• {item}</Text>
          ))}
          <Text style={[styles.swotTitle, { color: colors.text }]}>Weaknesses</Text>
          {asItems(swot.weaknesses).map((item) => (
            <Text key={`w-${item}`} style={[styles.swotItem, { color: colors.textSoft }]}>• {item}</Text>
          ))}
        </Surface>
      </View>

      <View>
        <SectionHeader
          eyebrow="Insights"
          title="Actionable direction"
          description="Priority-ranked strategic takeaways generated by the intelligence layer."
        />
        <View style={styles.list}>
          {insights.map((insight, index) => {
            const record = insight as Record<string, unknown>;
            return (
              <Surface key={`insight-${index}`} style={styles.insightCard}>
                <Text style={[styles.insightTitle, { color: colors.text }]}>{String(record.title ?? "Insight")}</Text>
                <Text style={[styles.insightMeta, { color: colors.textMuted }]}>
                  {sentenceCase(String(record.priority ?? "normal"))} priority · {sentenceCase(String(record.type ?? "signal"))}
                </Text>
                <Text style={[styles.insightBody, { color: colors.textSoft }]}>
                  {String(record.recommendation ?? record.description ?? "No recommendation available.")}
                </Text>
              </Surface>
            );
          })}
        </View>
      </View>

      <PrimaryButton label="Back to competitors" variant="secondary" onPress={() => router.back()} />
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  header: {
    gap: 10,
    paddingTop: 12,
  },
  kicker: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  body: {
    fontSize: 15,
    lineHeight: 24,
  },
  grid: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    gap: 8,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: "900",
  },
  swotCard: {
    gap: 10,
  },
  swotTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  swotItem: {
    fontSize: 14,
    lineHeight: 22,
  },
  list: {
    gap: 12,
  },
  insightCard: {
    gap: 8,
  },
  insightTitle: {
    fontSize: 17,
    fontWeight: "800",
  },
  insightMeta: {
    fontSize: 13,
    lineHeight: 20,
  },
  insightBody: {
    fontSize: 14,
    lineHeight: 22,
  },
});
